In [18]:
print("Hello\nWorld")

Hello
World


In [20]:
type (11)

int

In [21]:
type(21.1)

float

In [22]:
type("hello")

str

In [23]:
type(True)

bool

In [24]:
type(False)

bool

In [25]:
float(2)

2.0

In [27]:
int(23.675)

23

In [30]:
age = 25
print("I am " + str (age) + "years old.")

I am 25years old.


In [31]:
age = 25
print(f"I am {age} years old.")

I am 25 years old.


In [32]:
int(True)

1

In [35]:
int(False)

0

In [36]:
20+5

25

In [37]:
5*3


15

In [38]:
"Michael Jackson"

'Michael Jackson'

In [44]:
word = "Michael Jackson"
print(word[0])

M


In [45]:
word = "Michael Jackson"
print(word[-4:-2])

ks


In [48]:
'Michael Jackson is best'
print ("Michael Jackson\n is best")

Michael Jackson
 is best


In [51]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
even_indexed_elements = numbers[::2]
print(even_indexed_elements)

[0, 2, 4, 6, 8]


In [53]:
"01234567".find('1')

1

In [54]:
"01234567".find('4')

4

In [55]:

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
sum_result=num1+num2
print(f"The sum of {num1} and {num2} is :{sum_result}")

Enter the first number:  1
Enter the second number:  2


The sum of 1 and 2 is :3


In [56]:
Ratings=(10,6,0,5,1,7,8,3,9)
tuple1 = ('disco',1,6,10,2)
type(Ratings)

tuple

In [57]:
type(tuple1)

tuple

In [59]:
tuple2= Ratings + tuple1

In [61]:
NT = (10, (2, 'pop', 'rock'), (1.2, 1.3), ('data', 3))

In [62]:
L1 = [1,2,3,4,5]
for number in L1:
  print(number)

1
2
3
4
5


In [63]:
word = "hello"
for letter in word:
    print(letter)

h
e
l
l
o


In [64]:
for i in range(5):
    print(i)

0
1
2
3
4


In [65]:
for i in range(5,-1,-1):
    print(i)

5
4
3
2
1
0


In [6]:
for i in range(5,-1,-2):
    print(i)

5
3
1


In [7]:
for i in range(1,5,1):
    print(i)

1
2
3
4


student ={'name':'Alice','age':20, 'grade':'A'}
for key, value in students.items():
    print(f"{key}: {value}")
    

In [10]:
for row in range(3):
    for col in range(3):
      print(f"Row: {row}, column: {col}")

Row: 0, column: 0
Row: 0, column: 1
Row: 0, column: 2
Row: 1, column: 0
Row: 1, column: 1
Row: 1, column: 2
Row: 2, column: 0
Row: 2, column: 1
Row: 2, column: 2


In [11]:
numbers = [1,2,3,4,5,6]
for number in numbers:
    if number % 2 == 0:
        print(f"{number} is even")

2 is even
4 is even
6 is even


In [13]:
count = 1
while count <= 5:
    print(count)
    count +=1

1
2
3
4
5


In [16]:
number = 1
while True:
    print(number)
    number += 1
    if number > 5:
        break

1
2
3
4
5


In [18]:
import numpy as np
a=[1,2,3,4,5]
x=np.array(a)
a

[1, 2, 3, 4, 5]

In [19]:
x.ndim

1

In [20]:
x = np.array([[1,2,3],[4,5,6]])
print(x.ndim)

2


In [22]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]


In [27]:
import numpy as np
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print("M\nMatrix Addition (A + B):")
C_add = A + B
print(C_add)

M
Matrix Addition (A + B):
[[ 6  8]
 [10 12]]


In [ ]:
 as np
imponumpyrt
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Addition (A + B):")
C_add = A + B
print(C_add)

Scalar = 3
print(f"\nScalar Multiplication (A * {Scalar}):")
C_scalar = A * Scalar
print(C_scalar)

Matrix Addition (A + B):
[[ 6  8]
 [10 12]]

Scalar Multiplication (A * 3):
[[ 3  6]
 [ 9 12]]


In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

print("\nElement-wise Squaring (A ** 2):")
C_Element = A ** 2
print(C_Element)


Element-wise Squaring (A ** 2):
[[ 1  4]
 [ 9 16]]


In [27]:
print("\nTranspose of Matrix A (A^T):")
A_transpose = A.T
print(A_transpose)


Transpose of Matrix A (A^T):
[[1 3]
 [2 4]]


In [29]:
a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b)

c = np.full((2,2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81781878 0.96885792]
 [0.91862592 0.9101614 ]]


In [31]:
a=np.array([[3,4,5,6],[4,5,6,7],[8,9,4,3],[3,5,6,7]],float)
b=np.array([4,5,6,7],float)
n=len(or j in range (i+1,n):
     a)
for i in range (n-1):
    f   if a[j,i]==0: continue
        factor=a[i,i]/a[j,i]
        for k in range (i,n):
            a[j,k]=a[j,k]*factor-a[i,k]
    print(a)

[[ 3.     4.     5.     6.   ]
 [ 0.    -0.25  -0.5   -0.75 ]
 [ 0.    -0.625 -3.5   -4.875]
 [ 0.     1.     1.     1.   ]]
[[ 3.    4.    5.    6.  ]
 [ 0.   -0.25 -0.5  -0.75]
 [ 0.    0.   -0.9  -1.2 ]
 [ 0.    0.    0.25  0.5 ]]
[[ 3.    4.    5.    6.  ]
 [ 0.   -0.25 -0.5  -0.75]
 [ 0.    0.   -0.9  -1.2 ]
 [ 0.    0.    0.   -0.6 ]]


In [2]:
import numpy as np
a=np.array([[3,4,5,6],[4,5,6,7],[8,9,4,3],[3,5,6,7]],float)
b=np.array([4,5,6,7],float)
n=len(a)
for i in range (n-1):
    for j in range (i+1,n):
        if a[j,i]==0: continue
        factor=a[i,i]/a[j,i]
        for k in range (i,n):
            a[j,k]=a[j,k]*factor-a[i,k]
        b[j]=b[i]-b[k]*factor
    print(a)
    print(b)

[[ 3.     4.     5.     6.   ]
 [ 0.    -0.25  -0.5   -0.75 ]
 [ 0.    -0.625 -3.5   -4.875]
 [ 0.     1.     1.     1.   ]]
[ 4.    -1.25   1.375 -3.   ]
[[ 3.    4.    5.    6.  ]
 [ 0.   -0.25 -0.5  -0.75]
 [ 0.    0.   -0.9  -1.2 ]
 [ 0.    0.    0.25  0.5 ]]
[ 4.   -1.25 -0.05 -2.  ]
[[ 3.    4.    5.    6.  ]
 [ 0.   -0.25 -0.5  -0.75]
 [ 0.    0.   -0.9  -1.2 ]
 [ 0.    0.    0.   -0.6 ]]
[ 4.   -1.25 -0.05 -7.25]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[2,-1,1],[3,0,-1]],float)
b=np.array([9,8,3],float)
print(a)
print(b)
n=len(a)
for i in range (n-1):
    for j in range (i+1,n):
        if a[j,i]==0: continue
        factor=a[j,i]/a[i,i]
        for k in range (i,n):
            a[j,k]=a[j,k]-a[i,k]*factor
        b[j]=b[j]-b[i]*factor
print(a)
print(b)
x = np.zeros(n)
print (x)
x[n-1]=b[n-1]/a[n-1,n-1]

for i in range(n-2,-1,-1):
    sum=0
    for j in range(i+1,n):
        sum = sum+a[i,j]*x[j]
    x[i]=(b[i]-sum)/a[i,i]
print(x)

print('\Required solution is: ')
for i in range(n):
          print('x%d = %0.2f' %(i,x[i]), end = '\t')
    



[[ 1.  2.  3.]
 [ 2. -1.  1.]
 [ 3.  0. -1.]]
[9. 8. 3.]
[[ 1.  2.  3.]
 [ 0. -5. -5.]
 [ 0.  0. -4.]]
[  9. -10. -12.]
[0. 0. 0.]
[ 2. -1.  3.]
\Required solution is: 
x0 = 2.00	x1 = -1.00	x2 = 3.00	

In [3]:
import numpy as np
A = np.array([[6,1,1],
              [4,-2,5],
              [2,8,7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [5]:
import numpy as np
a=np.array([[8,3,-2],[-4,7,5],[3,4,-12]])
b=np.array([9,15,35])
x=np.linalg.solve(a, b)
print(x)

[-0.58226371  3.22870478 -1.98599767]


In [17]:
import pprint
import numpy as np
from scipy.linalg import lu

A=np.array([[7,3,-1,2],[3,8,1,-4],[-1,1,4,-1],[2,-4,-1,1]])
P, L, U =lu(A)
print("A:",A)
print("L:",L)
print("U:",U)



A: [[ 7  3 -1  2]
 [ 3  8  1 -4]
 [-1  1  4 -1]
 [ 2 -4 -1  1]]
L: [[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
U: [[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.         -3.11377246]]


In [12]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve
A = np.array([[2,5,8,7],[5,2,2,8],[7,5,6,6],[5,4,4,8]])
b .a= nprray([1,1,1,1])
LU, piv = lu_factor(A)
L, U  n=p.tril(LU, k=-1) + np.eye(4), np.triu(LU)
print("L:",L)
print("U:",U)
print("LU:",LU)
print("piv:",piv)
x1 = lu_solve((LU,piv),b)
print("the solutions are",x1)

L: [[ 1.          0.          0.          0.        ]
 [ 0.28571429  1.          0.          0.        ]
 [ 0.71428571  0.12        1.          0.        ]
 [ 0.71428571 -0.44       -0.46153846  1.        ]]
U: [[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]]
LU: [[ 7.          5.          6.          6.        ]
 [ 0.28571429  3.57142857  6.28571429  5.28571429]
 [ 0.71428571  0.12       -1.04        3.08      ]
 [ 0.71428571 -0.44       -0.46153846  7.46153846]]
piv: [2 2 3 3]
the solutions are [ 0.05154639 -0.08247423  0.08247423  0.09278351]


In [13]:
import numpy as np
u=np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(u)

[[1 2 3]
 [0 5 6]
 [0 0 9]
 [0 0 0]]


In [14]:
import numpy as np
l=np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(l)

[[ 1  0  0]
 [ 4  5  0]
 [ 7  8  9]
 [10 11 12]]


In [15]:
import numpy as np
a=np.array([[2,5,8,7],[5,2,2,8],[7,5,6,6],[5,4,4,8]])

L=np.triu(A, k=-1)
print(L)

[[2 5 8 7]
 [5 2 2 8]
 [0 5 6 6]
 [0 0 4 8]]


In [22]:
def sum(a,b):
    c=a+b
    return c
sum(2,3)

5

In [24]:
def div(a,b):
    c=a/b
    return c
div(3,6)

0.5

In [9]:
import numpy as np

def check_consistency(A, b):
    AB = np.hstack((A, b.reshape(-1, 1)))
    print("Augmented Matrix [A | b]:\n", AB)

    rank_A = np.linalg.matrix_rank(A)
    print("Rank of Matrix A:", rank_A)
    rank_AB = np.linalg.matrix_rank(AB)
    print("Rank of Matrix AB:", rank_AB)
    print("Number of unknowns:", len(A))

    if rank_A == rank_AB:
        print("The system is consistent.")
        if rank_A == len(A):
            print("The system has a unique solution.")
            x = solve(A, b)
        else:
            x = "The system has infinitely many solutions."
    else:
        x = "The system is inconsistent."

    return x

A = np.array([[0, 1, 1],
              [1, 1, 0],
              [1, 0, 1]])
b = np.array([3.65, 1.55, 0])

result = check_consistency(A, b)
print("\nResult:", resulAugmented Matrix [A | b]:
 [[0.   1.   1.   3.65]
 [1.   1.   0.   1.55]
 [1.   0.   1.   0.  ]]
Rank of Matrix A: 3
t)


Augmented Matrix [A | b]:
 [[0.   1.   1.   3.65]
 [1.   1.   0.   1.55]
 [1.   0.   1.   0.  ]]
Rank of Matrix A: 3
Rank of Matrix AB: 3
Number of unknowns: 3
The system is consistent.
The system has a unique solution.

Result: [-1.05  2.6   1.05]


In [7]:
import numpy as np
from scipy.linalg import solve

def check_linearcombination(A, b):
    AB = np.hstack((A, b.reshape(-1, 1)))
    print("Augmented Matrix [A|b]:\n", AB)

    rank_A = np.linalg.matrix_rank(A)
    print("The rank of Matrix A:", rank_A)
    
    rank_AB = np.linalg.matrix_rank(AB)
    print("The rank of Matrix AB:", rank_AB)
    
    print("Number of unknowns:", len(A))

    if rank_A == rank_AB:
        if rank_A == len(A):
            print("v can be expressed as a linear combination of A, and the solution is as follows:")
            x = solve(A, b)
        else:
            x = "v can be expressed as a linear combination of A, but there are infinite solutions."
    else:
        x = "v cannot be expressed as a linear combination of A."
    
    return x

u1 = np.array([0, 1, 1])
u2 = np.array([1, 1, 0])
u3 = np.array([1, 0, 1])
v = np.array([3.65, 1.55, 0])

A = np.column_stack((u1, u2, u3))
result = check_linearcombination(A, v)
print(result)


Augmented Matrix [A|b]:
 [[0.   1.   1.   3.65]
 [1.   1.   0.   1.55]
 [1.   0.   1.   0.  ]]
The rank of Matrix A: 3
The rank of Matrix AB: 3
Number of unknowns: 3
v can be expressed as a linear combination of A, and the solution is as follows:
[-1.05  2.6   1.05]


In [5]:
import numpy as np

def is_spans(vectors):
    rank_A=np.linalg.matrix_rank(vectors)
    print("The rank of a Matrix A",rank_A)
    L=len(vectors[0])
    print("no of elements in a vector",L)
    if rank_A==L:
        x="The given vectors spans the vector space V"
        return x
    else:
        x="The given vectors does not spans the vector space V"
        return x

vectors = [
    [1,0,0],
    [0,1,2]
]
print(is_spans(vectors))

print("")

vectors = [
    [1,0,0],
    [0,1,0],
    [0,2,1],
    [0,2,1]
]
print(is_spans(vectors)) 

The rank of a Matrix A 2
no of elements in a vector 3
The given vectors does not spans the vector space V

The rank of a Matrix A 3
no of elements in a vector 3
The given vectors spans the vector space V


In [4]:
import numpy as np

def is_Basis(vectors):
    rank_A=np.linalg.matrix_rank(vectors)
    print("The rank of a Matrix A",rank_A)
    AB=len(vectors[0])
    print("Number of elements in each vector",AB)
    n=np.shape(vectors)[0]
    print("no of unknowns",n)
    if rank_A==AB==np.shape(vectors)[0]:
        x="The given vectors Basis"
        return x
    else:
        x="The given vectors does not form Basis"
        return x

vectors = [
    [1,0,0],
    [0,1,2]
]
print(is_Basis(vectors))

print("")

vectors = [
    [1,0,0],
    [0,1,0],
    [0,2,1],
    [0,2,1]
]
print(is_Basis(vectors)) 

The rank of a Matrix A 2
Number of elements in each vector 3
no of unknowns 2
The given vectors does not form Basis

The rank of a Matrix A 3
Number of elements in each vector 3
no of unknowns 4
The given vectors does not form Basis


In [4]:
from sympy import*
M = Matrix([[1,2,3,0,0],[4,10,0,0,1]])
print("Matrix M",M)
m,n=M.shape
print(f"there are {m} rows and {n} columns")
MT=M.T
print("Transpose of a Matrix M",MT)
print("")
C_M=M.columnspace()
print("column space of M/n",C_M)
print("Dimension of column space of M/n",M.rank())
print("------------------------------------------")
print("------------------------------------------")
N_M=M.nullspace()
print("null space of M/n",N_M)
print("Dimension of null space of M/n",M.rank())
print("------------------------------------------")
print("------------------------------------------")

Matrix M Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
there are 2 rows and 5 columns
Transpose of a Matrix M Matrix([[1, 4], [2, 10], [3, 0], [0, 0], [0, 1]])

column space of M/n [Matrix([
[1],
[4]]), Matrix([
[ 2],
[10]])]
Dimension of column space of M/n 2
------------------------------------------
------------------------------------------
null space of M/n [Matrix([
[-15],
[  6],
[  1],
[  0],
[  0]]), Matrix([
[0],
[0],
[0],
[1],
[0]]), Matrix([
[   1],
[-1/2],
[   0],
[   0],
[   1]])]
Dimension of null space of M/n 2
------------------------------------------
------------------------------------------


In [12]:
import numpy as np
vectors = [
    [1,0,0],
    [0,2,0]
]
dot_product = np.dot(vectors[0] , vectors[1])
print(f"The dot product between two vectors is{dot_product}")

norm_v0=np.linalg.norm(vectors[0])
print(f"The lenght of the vectors{vectors[0]} is {norm_v0}")

norm_v1=np.linalg.norm(vectors[1])
print(f"The lenght of the vectors{vectors[1]} is {norm_v1}")

if dot_product==0:
    if norm_v0==norm_v1==1:
        print("The given two vectors are orthogonal and orthonormal")
    else:
        print("The given two vectors are orthogonal but length of one vector is not 1 so not orthonormal")
else:
    if norm_v0==v1==1:
        print("The length of given two vectors are 1 but dot product is not zero so, not orthgonal hence not orthogonal")
    else:
        print("The length of the vector in vectors are not 1 and also dot product is not zero so, not orthgonal hence not orthogonal")

        

The dot product between two vectors is0
The lenght of the vectors[1, 0, 0] is 1.0
The lenght of the vectors[0, 2, 0] is 2.0
The given two vectors are orthogonal but length of one vector is not 1 so not orthonormal


In [8]:
import numpy as np

def is_orthogonalset(vectors):
    vectors = np.array(vectors)
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            dot_product = np.dot(vectors[i], vectors[j])
            if not np.isclose(dot_product, 0):
                return false
    return true 
vectors = [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
if is_orthogonalset(vectors):
    print("The set of vectors is orthogonal set.")
else:
    print("The set of vectors is not orthogonal set.")

The set of vectors is orthogonal set.


In [13]:
import numpy as np

def is_orthonormal_set(vectors):
    vectors = np.array(vectors)
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            dot_product = np.dot(vectors[i], vectors[j])
            norm_vi=np.linalg.norm(vectors[i])
            norm_vj=np.linalg.norm(vectors[j])
            if dot_product !=0 or norm_vi!=1 or norm_vj!=1:
                return false
    return true 
vectors = [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
if is_orthonormal_set(vectors):
    print("The set of vectors is orthonormal set.")
else:
    print("The set of vectors is not orthonormal set.")

The set of vectors is orthonormal set.


In [19]:
import numpy as np

def is_orthonormalset(vectors):
    vectors = np.array(vectors)
    orthogonalset=is_orthogonalset(vectors)
    if orthogonalset==True:
        count=0
    for i in range(len(vectors)):
        norm_vi=np.linalg.norm(vectors[i])

        if (norm_vi==1):
            count=count+1
        else:
            return False
    return count
      
vectors = [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
if is_orthogonalset(vectors):
    if is_orthonormal_set(vectors)==len(vectors):
        print("The set of vectors is orthogonal and orthonormal set.")
    else:
        print("The set of vectors is orthonormal set but not orthonormal set.")
else:
    print("The set of vectors neither orthonormal set nor orthonormal set.")


The set of vectors is orthonormal set but not orthonormal set.


In [22]:
import numpy as np

def is_orthonormalset(vectors):
    vectors = np.array(vectors)
    orthogonalset=is_orthogonalset(vectors)
    if orthogonalset==True:
        for i in range(len(vectors)):
            norm_vi=np.linalg.norm(vectors[i])
            if (norm_vi==1):
                return False
    return True
      
vectors = [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
if is_orthogonalset(vectors):
    if is_orthonormal_set(vectors)==len(vectors):
        print("The set of vectors is orthogonal and orthonormal set.")
    else:
        print("The set of vectors is orthonormal set but not orthonormal set.")
else:
    print("The set of vectors neither orthonormal set nor orthonormal set.")


The set of vectors is orthonormal set but not orthonormal set.


In [23]:
import numpy as np
def IsOrthogonalBasis(vectors):
    if is_orthogonalset(vectors):
        print("The set is linear independent")
        if len(vectors)==len(vectors[0]):
            x="and it spans the vector space V. Hence it forms orthoganal basis for vector space"
        else:
            x="and it spans the subspace W of vector space V. Hence it forms orthoganal basis subspace"
    else:
        x="The set is not orthogonal basis"
    return x
vectors = [
    [1,0,0],
    [0,1,0],
    [0,0,0]
]
print(f"The followings are the vector set{vectors}")   
IsOrthogonalBasis(vectors)
            

The followings are the vector set[[1, 0, 0], [0, 1, 0], [0, 0, 0]]
The set is linear independent


'and it spans the vector space V. Hence it forms orthoganal basis for vector space'

In [24]:
import numpy as np
def IsOrthonormalBasis(vectors):
    if is_orthonormalset(vectors):
        print("The set is linear independent")
        if len(vectors)==len(vectors[0]):
            x="and it spans the vector space V. Hence it forms orthonormal basis for vector space"
        else:
            x="and it spans the subspace W of vector space V. Hence it forms orthonormal basis subspace"
    else:
        x="The set is not orthonormal basis"
    return x
vectors = [
    [1,0,0],
    [0,1,0],
    [0,0,0]
]
print(f"The followings are the vector set{vectors}")   
IsOrthonormalBasis(vectors)
            

The followings are the vector set[[1, 0, 0], [0, 1, 0], [0, 0, 0]]


'The set is not orthonormal basis'

In [27]:
import numpy as np
def Is_OrthogonalCompliment(vectors1,vectors2):
    vectors1 = np.array(vectors1)
    vectors2 = np.array(vectors2)
    for i in range(len(vectors1)):
        for j in range(len(vectors2)): 
            dot_product = np.dot(vectors1[i],vectors2[j])
            if not np.isclose(dot_product, 0):
                return False
    return True
vectors1 = [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
vectors2 = [
    [0,1,0],
    [0,0,1]
]
if Is_OrthogonalCompliment(vectors1,vectors2):
    print("The set of vectors is orthogonal complement.")
else:
    print("The set of vectors is not orthogonal complement.")



The set of vectors is not orthogonal complement.


In [28]:
import numpy as np
def proj(y,u):
    y=np.array(y)
    u=np.array(u)
    proj_y=(np.dot(y,u)/np.dot(u,u))*u
    return proj_y
u=[1,2,3]
print(f"The vectors u is {u}")
y=[1,2,3]
print(f"The given vectors y is {y}")
print(f"The projection of y on a set of vectors is {proj(y,u)} ")

The vectors u is [1, 2, 3]
The given vectors y is [1, 2, 3]
The projection of y on a set of vectors is [1. 2. 3.] 
